title: Cephas Musafiri
email: cephasmusafiri@gmail.com
description: Research Assistant specializing in Public Economics, State Capacity, and Applied Microeconometrics.
theme: minima
plugins:
  - jekyll-feed
